define(
{
    "root": {
        "color":                        "Point color",
        "background_color":             "Background color",
        "grid_background":              "Grid background color",
        "grid_outline":                 "Grid outline color",
        "grid_lines":                   "Grid lines color",
        "point_label_font":             "Point label font",
        "point_label_color":            "Point label color",
        "point_size":                   "Point size",
        "min_point_size":               "Min point size",
        "max_point_size":               "Max point size",
        "labels_visible":               "Show point labels",
        "label_placement":              "Label placement",
        "label_placement_top_left":     "Top left",
        "label_placement_bottom_left":  "Bottom left",
        "label_placement_top_right":    "Top right",
        "label_placement_bottom_right": "Bottom right",
        "title_font":                   "Title label font",
        "title_color":                  "Title & tick color",
        "animation_duration":           "Animation duration",
        "group_general":                "General",
        "group_background":             "Background",
        "group_points":                 "Points",
        "group_titles":                 "Titles",
        "group_visualization":          "Visualization",
        "slot_points":                  "Points",
        "slot_points_description":      "Determines the shapes to be displayed",
        "slot_top":                     "Top",
        "slot_top_description":         "Measure value at the top vertex of the triangle",
        "slot_left":                    "Left",
        "slot_left_description":        "Measure value at the left vertex of the triangle",
        "slot_right":                   "Right",
        "slot_right_description":       "Measure value at the right vertex of the triangle",
        "slot_color":                   "Color",
        "slot_color_description":       "Determines the color of the shapes",
        "slot_size":                    "Size",
        "slot_size_description":        "Determines the size of the shapes"
    }//,
    // "nl": true
} );
